config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/boards', to: 'boards#show'
  get '/index', to: 'boards#index'
  get '/posts', to: 'posts#show'
  get '/replies', to: 'posts#show'
  resources :posts
  resources :boards
  resources :replies
  resources :subadmin
end

app/models/board.rb
class Board < ActiveRecord::Base
    has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :board
    belongs_to :user
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/seccion.rb
class Seccion < ActiveRecord::Base
end

app/models/subadmin.rb
class Subadmin < ActiveRecord::Base
  belongs_to :user1
  belongs_to :user2
  belongs_to :board
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :login
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.find_for_database_authentication warden_condition
    conditions = warden_condition.dup
    login = conditions.delete(:login)
    where(conditions).where(
      ["lower(username) = :value OR lower(email) = :value", 
      {value: login.strip.downcase}]).first
  end
end

app/models/voto.rb
class Voto < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,
        keys: [:username, :email, :password, :password_confirmation])

      devise_parameter_sanitizer.permit(:sign_in,
        keys: [:login, :password, :password_confirmation])

      devise_parameter_sanitizer.permit(:account_update, 
        keys: [:username, :email, :password_confirmation, :current_password])
    end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    def index
       @boards = Board.all
    end

    def show
        @board = Board.find(params[:id])
        @posts = Post.where(board_id: @board).order("post_datetime DESC")
        @users = User.all
    end

    def new
        @board = Board.new
    end

    def create
        @board = Board.new(board_params)
        @board.user_id = current_user.id

        if @board.save
          redirect_to @board
        else
          render :new
        end
    end

    private
        def board_params
            params.require(:board).permit(:name)
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def home
        render html: "<h1>Hola, Rails!</h1>".html_safe
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    #before_action :authenticate_user!, except: [:show]
    
    def show
        @post = Post.find(params[:id])
        @users = User.all
        @replies = Reply.where(post_id: params[:id])
        @board = Board.find(@post.board_id)
    end

    def new
        @board_id = params[:board_id]
        @post = Post.new
    end

    def destroy
        post = Post.find(params[:id])
        board = Board.find(post.board_id)
        post.destroy
        redirect_to board
    end

    def create
        @post = Post.new(post_params)
        @post.post_datetime = Time.now
        @post.user_id = current_user.id

        if @post.save
          redirect_to @post
        else
          render :new
        end
    end

    private
        def post_params
            params.require(:post).permit(:title, :content, :imagen_url, :board_id)
        end
    
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

    def new
        @post_id = params[:post_id]
        @reply = Reply.new
    end

    def destroy
        reply = Reply.find(params[:id])
        post = Post.find(reply.post_id)
        reply.destroy
      
        redirect_to post
      end

    def create
        @reply = Reply.new(reply_params)
        @reply.reply_datetime = Time.now
        @reply.user_id = current_user.id

        if @reply.save
            redirect_to Post.find(@reply.post_id)
          else
            render :new
          end
    end

    private
        def reply_params
            params.require(:reply).permit(:contenido, :post_id)
        end
    
end

app/controllers/subadmin_controller.rb
class SubadminController < ApplicationController
    def new
        @board_id = params[:board_id]
        @subadmin = Subadmin.new
    end

    def create
        @subadmin = Subadmin.new(subadmin_params)
        @subadmin.user1_id = current_user.id

        if @subadmin.save
            redirect_to '/index'
          else
            render :new
          end
    end

    private
        def subadmin_params
            params.require(:subadmin).permit(:user2_id, :board_id)
        end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/secciones_helper.rb
module SeccionesHelper
end

app/helpers/subadmin_helper.rb
module SubadminHelper
end

app/views/boards/index.html.erb
<br>
<h1><center> Índice </center></h1>

<tbody>

<% if signed_in? %>
    <center> <%= link_to "Crear un board", new_board_path %></center>
<% end %>

<ul style = "margin: 20px; border:2px solid gray;">
    <% @boards.each do |board| %>
        <li><%= link_to board.name, board %></li> 
    <% end %>
</ul>

</tbody>

app/views/boards/new.html.erb
<center><h1>Nuevo Board</h1>
<br><br><br>
<%= form_for @board do |f| %>
  <div>
    <%= f.label :Nombre%>
    <br>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.submit %>
  </div>
  </center>
<% end %>

app/views/boards/show.html.erb
<div align="right">
    <% if signed_in? %>
        <% if current_user.id == @board.user_id%>
            <%= link_to "Entregar subadministración", new_subadmin_path(board_id: @board.id) %>
        <% end %>
    <% end %>
</div> 

<h1><center> <%= @board.name %> </center></h1>

<center> <%= link_to "Crear un post", new_post_path(board_id: @board.id) %></center>

<tbody>

<% @posts.each do |post| %>
    <p style = "margin: 20px; border:2px solid gray;">       
        <font color="red"> <%= @users.find(post.user_id).username %> </font>
        <b><%= post.title %></b> 
        <font color="gray"> <%= post.post_datetime %> </font>
        
        <%= link_to "Comentarios", post%>
        <% if signed_in? %>
            <% if post.user_id == current_user.id || current_user.id == @board.user_id%>
                <%= link_to "Eliminar", post, method: :delete, data: { confirm: "¿Estás seguro de eliminar este post?" } %> 
            <% end %>
        <% end %>
        
        <br>
        <%= post.content %>
    </p> 
<% end %>
</tbody>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bdtrue</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="background-color:lightblue;text-align:left;">

  <% if request.url != 'http://localhost:3000/index' %>
    <%= link_to "Índice", '/index' %>
  <% end %>

  <span style="float:right;">
    <% if signed_in? %>
      <%= link_to current_user.username, edit_user_registration_path(current_user) %>
      <%= link_to "(salir)", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Registrarse", new_user_registration_path %>
      <%= link_to "Ingresar", new_user_session_path %>
    <% end %>
  </span>


<%= yield %>

</body>
</html>

app/views/posts/new.html.erb
<h1>Nuevo Post</h1>
<%= form_for @post do |f| %>
  <div>
    <%= f.label :Título %>
    <br>
    <%= f.text_field :title %>
    <br><br>
  </div>

  <div>
    <%= f.label :Contenido%>
    <br>
    <%= f.text_area :content %>
    <br><br>
  </div>

  <div>
    <%= f.label :imagen_url %>
    <br>
    <%= f.text_field :imagen_url %>
    <br><br>
  </div>
  
  <div>
  <%= f.hidden_field :board_id, value: @board_id %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/show.html.erb
<h1><center> <%= @board.name %> </center></h1> 

<p style = "margin: 20px; border:2px solid gray;">


    <font color="red"> <%= @users.find(@post.user_id).username %> </font>
    <b><%= @post.title %></b> 
    <font color="gray"> <%= @post.post_datetime %> </font>

    <% if signed_in? %>
        <% if @post.user_id == current_user.id || current_user.id == Board.find(@post.board_id).user_id  %>
            <%= link_to "Eliminar", @post, method: :delete, data: { confirm: "¿Estás seguro de eliminar este post?" } %> 
        <% end %>
    <% end %>
    <br>
    <%= @post.content %>
    <center> <%= link_to "Responde a este post", new_reply_path(post_id: @post.id) %></center>
        <p style = "margin: 20px">
        <% @replies.each do |reply| %>    
            <font color="red"> <%= @users.find(reply.user_id).username %> </font>
            <font color="gray"> <%= reply.reply_datetime %> </font>                        
        
            <% if signed_in? %>
                <% if reply.user_id == current_user.id || current_user.id == Board.find(@post.board_id).user_id %>
                    <%= link_to "Eliminar", reply, method: :delete, data: { confirm: "¿Estás seguro de eliminar este comentario?" } %> 
                <% end %>
            <% end %>

            <br>
            <%= reply.contenido %>
            <br><br>
        <% end %>
        </p>


</p> 

app/views/replies/new.html.erb
<h1>Nueva Respuesta</h1>

<%= form_for @reply do |f| %>
  <div>
    <%= f.label :Comentario %>
    <%= f.text_area :contenido %>
  </div>

  <div>
  <%= f.hidden_field :post_id, value: @post_id %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/secciones/index.html.erb
<h1><center> Índice </center></h1>

<tbody>
<p style = "margin: 20px; border:2px solid gray;">
<ul style = "margin: 20px; border:2px solid gray;">
    <% @secciones.each do |seccion| %>
        <li><%= seccion.nombre %></li> 
    <% end %>
</ul>
</p>         

</tbody>

app/views/secciones/show.html.erb
<h1><center> <%= @seccion.nombre %> </center></h1>

<center> <%= link_to "Crear un post", new_post_path %></center>

<tbody>


<% @posts.each do |post| %>
    <p style = "margin: 20px; border:2px solid gray;">
        <%= link_to "post", post %>
        
        <font color="red"> <%= @users.find(post.user_id) %> </font>
        <b><%= post.title %></b> 
        <font color="gray"> <%= post.post_datetime %> </font>
        <%= link_to "Comentarios", post%>
        <% if signed_in? %>
            <%= link_to "Eliminar", post, method: :delete, data: { confirm: "¿Estás seguro de eliminar este post?" } %> 
        <% end %>
        <br>
        <%= post.content %>
    </p> 
<% end %>
</tbody>

app/views/subadmin/new.html.erb
<h1>Otorgar subadministración de board</h1>

<%= form_for @subadmin do |f| %>
    <div>
      <%= f.label :user %>
      <%= f.text_field: user2_id%>
    </div>
  
    <div>
    <%= f.hidden_field :board_id, value: @board_id %>
    </div>
  
    <div>
    <%= f.submit %>
    </div>
<% end %>